--- 
title: "Time Series for Beginners"
author: "Jake Esprabens, Ari Arango, Joshua Kim"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a short guide to learning the basic concepts of time series while also implementing these procedures in R."
---

# Preface {-}

This book is created with an objective to clearly explain the basics of time series analysis.  The inspiration came from taking a time series course and constantly getting confused by the theory.  Often, time series can be a tricky subject; therefore, this book will try to explain the essentials of time series using R. 

Time series is an immense subject with so much to it; therefore, we won't be able to cover all of it in this book.  We will solely focus on what we believe is the most important to provide you with the ability to forecast with time series.

Make sure to check out our correspoding API package and Stock Shiny App to explore real world uses of time series.  This package will allow you to directly grab the most recent data on stock prices around the world.  Moreover, the Shiny App will allow you to visualize and interact with this data as a time series and predict how the stock prices will move in the future!

I recommend installing these 3 packages before we get started:

```{r, eval = FALSE}
library(tidyverse)
library(ggfortify)
library(forecast)
```

